### PR TITLE
Add automation to release new crates

### PR DESCRIPTION
**Pull request by gjtorikian**
👋  This is an automation to make cutting new releases a little easier. It's a variation on a workflow I use [in my Ruby gem releases](https://github.com/yettoapp/actions/blob/main/.github/workflows/ruby_gem_release.yml). 

Note that this release workflow only executes manually, ie. you have to still push the `Release workflow` button:

Screenshot 2024-04-09 at 07 53 58

 Step by step, it:
 
1. Grabs the repo, sets up rust
2. Gets the current `version` of the project defined in Cargo.toml
3. Generates a changelog/readme 
4. Pushes those to the repo
3. Publishes the crate
4. Creates a tag, and publishes the release on GitHub

Along the way, I also see the opportunity to add more automations around dependency management.

I haven't tested this yet, but I will do so by changing the version number to something like `0.$LATEST.0.alpha` if the PR is desired!

### CODE REVIEW

**Comment by kivikakk** [comment]
This looks lovely! It'd be great to see a test run.

Also, looks like there's still some Rubygems stuff in the `publish` job?

**Comment by gjtorikian** [comment]
> It'd be great to see a test run.

I swear this isn't a social engineering phishing attempt! 😅  But I just realized I don't have the ability to add secret tokens to this repo, so I can't add my own crates.io API key to use here—so it won't ever publish. 

If you could add `CRATES_IO_TOKEN` as a secret variable, I can move forward with testing the run!

**Comment by kivikakk** [comment]
😅 Done!

**Comment by gjtorikian** [comment]
Sigh. Looks like you can't manually run a workflow—even if it's set to `workflow_dispatch`—until it's merged in the main branch.

In theory, I think all of this ought to work. Happy to make changes, and then once it's merged, actually attempt the automation? I'm not sure how else to test this.

**Comment by kivikakk** [comment]
Of course, please go ahead!

**Pull request merged**
