### PR TITLE
update-readme: use Comrak as an example of Markdown editing

### LINKED ISSUE #181: help: markdown->modify->markdown
Hey there, I have an odd use case and I spent last few hour trying to figure it out. Basically, I want to take a markdown file, edit it's syntax tree and parse it back to markdown.

So I wonder if any one can point me or show me how I can  essentially do markdown->modify->markdown 

Thanks

### PR DESCRIPTION
**Pull request by kivikakk**
We currently use a small Ruby script which depends on [commonmarker](https://github.com/gjtorikian/commonmarker) to update the `comrak --help` output included in the README.

Change this to an example that actually uses Comrak to show how to do CommonMark AST editing.

Fixes #181 by way of example. :) Hope this helps, @tami5.

### CODE REVIEW

**Comment by tami5** [comment]
> See #184 for an example of this!

😱😱 I'm so amazed of how simple ir turned out to be.

@kivikakk Thanks so much. Honestly, Great work!

**Comment by tami5** [comment]
:thinking: so I ran to this issue of not being able to access heading content. Any ideas @kivikakk :pray:

**Comment by kivikakk** [comment]
@tami5 Does https://github.com/kivikakk/comrak/pull/175#issuecomment-800698508 help you any?

**Comment by tami5** [comment]
Kinda, I'm trying to understand how I can get the title as well as the content of it until the next heading. Here what I managed todo so far

```rs

fn get_sections_and_content(content: &str) -> Option<HashMap<String, String>> {
    let arena = Arena::new();
    let doc = parse_document(&arena, content, &ComrakOptions::default());
    let mut result = HashMap::new();

    fn collect_text<'a>(node: &'a AstNode<'a>, output: &mut Vec<u8>) {
        match node.data.borrow().value {
            NodeValue::Text(ref literal) | NodeValue::Code(ref literal) => {
                output.extend_from_slice(literal)
            }
            NodeValue::LineBreak | NodeValue::SoftBreak => output.push(b' '),
            _ => {
                for n in node.children() {
                    collect_text(n, output);
                }
            }
        }
    }

    for node in doc.children() {
        let header = match node.data.clone().into_inner().value {
            NodeValue::Heading(c) => c,
            _ => continue,
        };

        if header.level != 2 {
            continue;
        }

        let mut text = Vec::new();
        collect_text(node, &mut text);

        // The input was already known good UTF-8 (document: &str) so comrak
        // guarantees the output will be too.
        result.insert(String::from("??"), String::from_utf8(text).unwrap());
    }

    if result.is_empty() {
        return None;
    }

    Some(result)
}

```

So far I got one 2nd level header `{"??":x"Timeline"}`

**Comment by tami5** [comment]
Okay I manged to get all the sections so far.

```rs
pub fn read(
        &mut self,
        _sec: &str,
    ) -> Result<HashMap<String, String>, Error> {
        let mut hmap = HashMap::new();
        let current = {
            let mut content = String::new();
            BufReader::new(fs::File::open(self.get_filepath())?)
                .read_to_string(&mut content)?;

            content.truncate(content.len() - 1);
            content
        };

        let arena = Arena::new();

        let doc = parse_document(&arena, &current, &ComrakOptions::default());

        fn collect_text<'a>(node: &'a AstNode<'a>, output: &mut Vec<u8>) {
            match node.data.borrow().value {
                NodeValue::Text(ref literal) | NodeValue::Code(ref literal) => {
                    output.extend_from_slice(literal)
                }
                NodeValue::LineBreak | NodeValue::SoftBreak => {
                    output.push(b' ')
                }
                _ => {
                    for n in node.children() {
                        collect_text(n, output);
                    }
                }
            }
        }

        fn collect_sections<'a>(
            node: &'a AstNode<'a>,
            hmap: &mut HashMap<String, String>,
        ) {
            if let NodeValue::Heading(ref mut heading) =
                node.data.clone().into_inner().value
            {
                if heading.level == 2 {
                    let mut output = Vec::new();
                    collect_text(node.to_owned(), &mut output);
                    hmap.insert(
                        String::from_utf8(output).unwrap(),
                        "??".to_string(),
                    );
                }
            }
            for c in node.children() {
                collect_sections(c, hmap);
            }
        }

        collect_sections(doc, &mut hmap);

        Ok(hmap)
    }

```

**Comment by tami5** [comment]
@kivikakk ping

**Comment by tami5** [comment]
I think I'm trying to return a section with all it's node until the next section. Couldn't figure it out how do this yet

**Comment by kivikakk** [comment]
You will need to do some graph operations on the AST if you want to do this in a non-hacky way. Alternatively, for a hacky way you could locate headers and insert unique identifying strings in them, and then convert to HTML (or back to CommonMark) and then use regular substring operations.

Either way, it is unfortunately a bit of work, and I do not have the time to create a solution for you myself.

**Comment by tami5** [comment]
Thanks @kivikakk. This bit is all I need.

**Pull request merged**
