### PR TITLE
Make `ComrakExtensionOptions` non-exhaustive

### LINKED ISSUE #303: `shortcodes` feature isn't additive in `ComrakExtensionOptions`
Enabling the `shortcodes` feature can break existing code that compiles without it. E.g.

```rust
fn main() {
    let _ = ComrakExtensionOptions {
        strikethrough: false,
        tagfilter: false,
        table: false,
        autolink: false,
        tasklist: false,
        superscript: false,
        header_ids: None,
        footnotes: false,
        description_lists: false,
        front_matter_delimiter: None,
    };
}
```

compiles fine. However, enabling the `shortcodes` feature would then cause it to hit a compiler error about missing the `shortcodes` field :crying_cat_face: 

Simply switching the `ComrakExtensionOptions` struct to be `#[non_exhaustive]` would be enough to fix the issue, and since `ComrakExtensionOptions` impls `Default` it should still be easy for people to construct it however they please

I'd be happy to make a PR if that seems like a sensible solution

### PR DESCRIPTION
**Pull request by CosmicHorrorDev**
Resolves #303

_Note: This is a breaking change, so it will require a breaking semver bump on next release_

I would also be willing to add builders for constructing all parts of `ComrakOptions` which is a bit more ergonomic to construct things with. All intermediate states of constructing `ComrakOptions` are valid, so they can just be implemented with setters on the structs instead of requiring a separate type

### CODE REVIEW

**Comment by tgross35** [comment]
I am not a maintainer (no connection to the project) but would you maybe consider adding it to all the config structs?

```
ComrakExtensionOptions
ComrakOptions
ComrakParseOptions
ComrakPlugins
ComrakRenderOptions
ComrakRenderPlugins
```

If there is to be a one-time breaking change for exhaustiveness, may as well apply it to everything that might want to add options in the future

**Comment by kivikakk** [comment]
> If there is to be a one-time breaking change for exhaustiveness, may as well apply it to everything that might want to add options in the future

I agree. I'll rebase this shortly and add those before I merge.

**Comment by kivikakk** [comment]
I've decided to leave the top-level `Options` struct out of this change for now.

**Comment by CosmicHorrorDev** [comment]
@kivikakk are you fine with me adding builders for the non-exhaustive options to make them less verbose to construct?

**Comment by kivikakk** [comment]
I'm just rebasing @YJDoc2's #292 now! :)

**Comment by CosmicHorrorDev** [comment]
Oh I somehow missed that 😅

Thanks for the great library btw!

**Comment by tgross35** [comment]
> Thanks for the great library btw!

Agreed, we apprecaite it!

**Comment by kivikakk** [comment]
Thanks both, that means a lot! The contributors list is getting longer — thanks for all your help. 😊

**Comment by digitalmoksha** [comment]
🤔 does this change require an update to the README?

**Comment by CosmicHorrorDev** [comment]
What part do you think would need a change? I don't see any code examples that use options or plugins aside from passing `Options::default()`

**Comment by digitalmoksha** [comment]
Ah you’re right. I was thinking the calling interface was changing.

**Pull request merged**
