### PR TITLE
Fix quadratic behaviour during emphasis processing

### LINKED ISSUE #24: Quadratic blowup on pathological input.
This takes ~1s on my machine:

```sh
perl -e 'print "_a* " x 40000' | time comrak >/dev/null
```
This allows a denial of service in any application using Comrak to process untrusted input, and thus prevents it from being used for that purpose, forcing the use of a C library such as cmark or MD4C instead.

### PR DESCRIPTION
**Pull request by kivikakk**
Fixes #24. Uses `remstack.rs` provided by @charliesome.

Not quite ready to merge yet; the correctness isn't 100%.

### CODE REVIEW

**Comment by kivikakk** [comment]
Next step: remove all messing around with indices entirely with opaque index/iterator type.

**Comment by zeantsoi** [comment]
This is a test^(of) this

**Comment by kivikakk** [comment]
@zeantsoi I can recommend using a test repo that doesn't already have users with notifications subscribed 🐰

**Comment by kivikakk** [comment]
RemStack idea needs some development still, so for now I've rewritten this to use an Arena, keeping a lot closer to the C codebase.

**Pull request merged**
