### PR TITLE
Feat/inplace: add new parameter `--inplace` (`-i`) for in-place formatting

### PR DESCRIPTION
**Pull request by bioinformatist**
Some clippy lints also have been fixed separately 😺

### CODE REVIEW

**Comment by kivikakk** [comment]
Thank you, this looks excellent.

I really appreciate the extra clippy fixes! I know in the past that some of these changes caused issues for people because it caused an increase in the MSRV (see https://github.com/kivikakk/comrak/issues/290), but I think it's been long enough that I'm happy to move on. Still, before I merge, I'm going to compare the lib and bin MSRVs before and after this change, just for my own reference, and make an appropriate declaration in Cargo.toml.

Thank you again! :white_heart:

**Comment by digitalmoksha** [comment]
@bioinformatist just curious, is there any difference between 

```
cargo run -- --inplace test.md
```

and

```
cargo run -- --to commonmark --output test.md test.md
```

It seems to work the same for me 🤔

**Comment by kivikakk** [comment]
It is the same, and it should be! And it's fine for it to be 👍  We could expand `-i` to allow specifying multiple files in future, or directories.

**Comment by digitalmoksha** [comment]
Sounds good to me. One thought I had was if the option was set we might be able to just set the proper `to` and `output` options internally.  But then we wouldn't be able to easily expand into multiple files, which would be desirable.

**Pull request merged**
