### PR TITLE
Sync with cmark-gfm-0.29.0.gfm.12

### PR DESCRIPTION
**Pull request by digitalmoksha**
This syncs up with `cmark-gfm 0.29.0.gfm.12`, and addresses https://github.com/kivikakk/comrak/issues/334

### CODE REVIEW

**Comment by gjtorikian** [comment]
I reckon CI is failing due to https://github.com/kivikakk/comrak/issues/342.

**Comment by digitalmoksha** [comment]
I think you’re right. What do you think the way forward is? Was the repo deleted by accident?On Sep 27, 2023, at 7:05 PM, Garen Torikian ***@***.***> wrote:﻿
I reckon CI is failing due to #342.

**Comment by charlottia** [comment]
CI now passing. I'll merge after review.

**Review by charlottia — APPROVED** [review]
I'm satisfied.

**Pull request merged**
