### PR TITLE
Keep track of "^" symbol when within footnotes

### PR DESCRIPTION
**Pull request by gjtorikian**
Should close https://github.com/kivikakk/comrak/issues/106. 

I haven't quite figured out how the parser should "write" to the resulting string, hence the draft state. Ideally the diff looks something like:

```diff
diff --git a/src/parser/inlines.rs b/src/parser/inlines.rs
index 28a1235..4732464 100644
--- a/src/parser/inlines.rs
+++ b/src/parser/inlines.rs
@@ -149,7 +149,22 @@ impl<'a, 'r, 'o, 'd, 'i, 'c, 'subj> Subject<'a, 'r, 'o, 'd, 'i, 'c, 'subj> {
                 }
             }
             '~' if self.options.extension.strikethrough => Some(self.handle_delim(b'~')),
-            '^' if self.options.extension.superscript => Some(self.handle_delim(b'^')),
+            '^' if self.options.extension.superscript => {
+                if !self.within_brackets {
+                    Some(self.handle_delim(b'^'))
+                } else {
+                    // something
+               }
```

### CODE REVIEW

**Comment by gjtorikian** [comment]
xref gjtorikian/commonmarker#217 fyi @dannyben

**Comment by gjtorikian** [comment]
Would it be possible to cut a new release with this? Thank you!

**Comment by kivikakk** [comment]
Of course — underway.

**Comment by kivikakk** [comment]
This is [0.16.0 on crates.io](https://crates.io/crates/comrak/0.16.0)!

**Pull request merged**
